# Docker Swarm Stack Configuration
# Deploy using: docker stack deploy -c docker-stack.yml survey-system

version: '3.9'

services:
  survey-app:
    image: yourusername/survey-system:latest
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        - "com.example.description=Survey System Application"
        - "com.example.version=1.0.0"
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - survey-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {if (r.statusCode !== 200) throw new Error(r.statusCode)})"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    volumes:
      - app-data:/app/data:rw
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Load balancer frontend
  loadbalancer:
    image: caddy:latest
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
    networks:
      - survey-network
    depends_on:
      - survey-app
    command: caddy run --config /etc/caddy/Caddyfile

networks:
  survey-network:
    driver: overlay
    driver_opts:
      com.docker.network.driver.overlay.vxlanid: "4096"

volumes:
  app-data:
    driver: local
  caddy-data:
    driver: local
